woowabros/nestjs-library-crud

spec/override-decorator/override.create.controller.spec.ts
spec/override-decorator/override.create.controller.ts
src/lib/crud.route.factory.ts

-   [x] Bugfix
- Key of `Method` enum is used as the key of `overrideMap`. But when using `overrideMap`, value of `Method` enum is preferred. Because of that, value of `isOverride` is always `false`.
- Change to use value of `Method` enum as the key of `overrideMap`.
-   [ ] Yes
-   [x] No

fix: override decorator does not work properly because of wrong method name

---

src/lib/interceptor/search-request.interceptor.ts

-   [x] Bugfix
- In `search-request.interceptor.ts`, it converts `nextCursor` to query's condition with this piece of code
```
const cursorCondition = Object.entries(lastObject).reduce(
(queryFilter, [key, operand]) => ({
...queryFilter,
[key]: {
operator: _.get(preCondition.order, 'key', …
```

fix: wrong condition from cursor in search request

---

package.json
spec/logging/logging.spec.ts
spec/pagination/pagination.spec.ts
spec/search/search-query-operator.spec.ts
src/lib/crud.policy.ts
src/lib/crud.service.ts
src/lib/dto/pagination-cursor.dto.ts
src/lib/interceptor/read-many-request.interceptor.spec.ts
src/lib/interceptor/read-many-request.interceptor.ts
src/lib/interface/pagination.interface.ts
src/lib/provider/pagination.helper.ts
src/lib/util.ts

-   [ ] Bugfix
Did not support `total` in cursor pagination.
When using cursor pagination, the request could not `check how many entities remained`.
Due to this requirement, we have provided `getTotalCountByCrudReadManyRequest` and `getTotalCountByCrudSearchRequest` in the …

feat: Officially support `total` in cursor pagination

---

spec/base/base.controller.read-one.spec.ts
spec/base/base.controller.spec.ts
spec/custom-entity/custom-entity.controller.read-many.spec.ts
spec/custom-entity/custom-entity.controller.read-one.spec.ts
spec/custom-entity/custom-entity.controller.search.spec.ts
spec/multiple-primary-key/multiple-primary-key.controller.read-one.spec.ts
spec/pagination/pagination.interceptor.spec.ts
spec/pagination/pagination.spec.ts
spec/read-many/read-many.controller.spec.ts
spec/response-interceptor/response-interceptor.spec.ts
spec/search/search-cursor-pagination.spec.ts
spec/search/search-query-operator.spec.ts
src/lib/abstract/abstract.pagination.spec.ts
src/lib/abstract/abstract.pagination.ts
src/lib/dto/pagination-cursor.dto.ts
src/lib/dto/pagination-offset.dto.ts
src/lib/request/read-many.request.ts

-   [ ] Bugfix
Reflect the comments from [the last review](https://github.com/woowabros/nestjs-library-crud/pull/267).
- https://github.com/woowabros/nestjs-library-crud/pull/267#discussion_r1295290293
- Reduce time spent on unit-tests.
Each `pagination dto` manages …

refactor: each `pagination dto` manages response`s metadata

---

src/lib/crud.route.factory.ts

-   [x] Bugfix
```
only: [Method.READ_MANY]
```
when only use ReadMany, swagger throws resolver error.
To fix this problem,
should be use `ReadOne together` or add `ApiExtraModels  Decorator`.
no error if only use ReadMany.
-   [ ] Yes
-   [x] No

fix: swagger resolver error, when only use readMany

---

spec/pagination/pagination.spec.ts
src/lib/interceptor/search-request.interceptor.ts

-   [x] Bugfix
1. If use `search` without conditions, a `where is not iterable` error occur.
2. If use `search` without conditions, the next cursor position will not be searched.
should be used search without conditions.
-   [ ] Yes
-   [x] No

fix: should be used search without conditions

---

src/lib/crud.route.factory.ts

-   [x] Bugfix
* In Swagger, when I click on `Search` request, it will open the detail of `Read Many` request instead.
* Change defined name of `Search` method in controller so Swagger can generate correct operation id.
-   [ ] Yes
-   [x] No

fix: correct search method operation id in swagger

---

package.json
spec/pagination/pagination.spec.ts
spec/read-many/read-many.controller.spec.ts
spec/search/search-cursor-pagination.spec.ts
src/lib/abstract/abstract.pagination.spec.ts
src/lib/abstract/abstract.pagination.ts
src/lib/crud.service.ts
src/lib/dto/pagination-cursor.dto.ts

-   [ ] Bugfix
The total of cursor pagination and offset pagination are different.
The total of offset pagination uses the total value of the first page as is, 
but the total of cursor pagination uses the value `minus the number of data`.
```
first page  (data length is 50)
- …
```

Redefines the total of cursor pagination.

---

spec/relation-entities/comment.entity.ts
spec/relation-entities/question.entity.ts
spec/relation-entities/relation-entities-read.spec.ts
spec/relation-entities/relation-entities-search.spec.ts
src/lib/interceptor/search-request.interceptor.spec.ts
src/lib/interceptor/search-request.interceptor.ts

-   [x] Bugfix
- In Search request, option `relations` does not work.
- `SearchRequestInterceptor` can get the `relations` configuration from CrudOption.
-   [ ] Yes
-   [x] No

fix: relations in crud option not work

---

spec/custom-entity/custom-entity.entity.ts
spec/multiple-primary-key/multiple-primary-key.entity.ts

-   [ ] Bugfix
use crypto.getRandomValues instead of Math.random
-   [ ] Yes
-   [x] No

feat: use crypto.getRandomValues instead of Math.random

---

src/lib/interceptor/create-request.interceptor.spec.ts
src/lib/interceptor/create-request.interceptor.ts
src/lib/interceptor/delete-request.interceptor.ts
src/lib/interceptor/read-many-request.interceptor.spec.ts
src/lib/interceptor/read-many-request.interceptor.ts
src/lib/interceptor/read-one-request.interceptor.spec.ts
src/lib/interceptor/read-one-request.interceptor.ts
src/lib/interceptor/recover-request.interceptor.ts
src/lib/interceptor/search-request.interceptor.spec.ts
src/lib/interceptor/search-request.interceptor.ts
src/lib/interceptor/update-request.interceptor.spec.ts
src/lib/interceptor/update-request.interceptor.ts
src/lib/interceptor/upsert-request.interceptor.spec.ts
src/lib/interceptor/upsert-request.interceptor.ts
src/lib/provider/pagination.helper.spec.ts

-   [ ] Bugfix
```
src/lib/interceptor/upsert-request.interceptor.ts:12:17 - error TS2742: The inferred type of 'UpsertRequestInterceptor' cannot be named without a reference to 'express-serve-static-core/node_modules/@types/qs'. This is likely not portable. A type annotation …
```

fix: ts2742

---

spec/entity-inheritance/child-entity-noname.spec.ts
spec/general-entity/without-name.spec.ts
src/lib/crud.route.factory.ts

-   [ ] Bugfix
Issue Number: https://github.com/woowabros/nestjs-library-crud/issues/383
Defining the `entity name is required`.
It can be used even `without defining an entity name`.
-   [ ] Yes
-   [x] No

feat: can be used without define entity name

---

.github/workflows/ci.yml
spec/pagination/pagination.interceptor.spec.ts
spec/pagination/pagination.spec.ts
spec/pgsql/pgsql.spec.ts
spec/search/search-complex-condition.spec.ts
spec/sub-path/sub-path-more-than-one-parent.spec.ts
spec/sub-path/sub-path-one-parent.spec.ts

-   [ ] Bugfix
unit-test fails on node v20.
unit-test succeeded on node v20.
`supertest` malfunctions due to changes in node20.
I'm guessing this is an issue with node v20 and not supertest. (https://github.com/nodejs/node/issues/47130)
I temporarily solve this issue by …

feat: unit-test on node v20

---

spec/listeners/allow-listeners.spec.ts
spec/listeners/disallow-listeners.spec.ts
spec/logging/logging.spec.ts
src/lib/crud.service.spec.ts
src/lib/crud.service.ts
src/lib/interceptor/create-request.interceptor.ts
src/lib/interceptor/delete-request.interceptor.ts
src/lib/interceptor/recover-request.interceptor.ts
src/lib/interceptor/update-request.interceptor.ts
src/lib/interceptor/upsert-request.interceptor.ts
src/lib/interface/decorator-option.interface.ts
src/lib/interface/request.interface.ts

-   [ ] Bugfix
Issue Number: #432 
controls the `Entity Listeners and Subscribers`.
A new option `listeners` has been added. For default values, refer to the TypeOrm setting.
-   [ ] Yes
-   [x] No

feat: controls listeners

---

spec/exclude-swagger/exclude-swagger.spec.ts
spec/swagger-decorator/swagger-decorator.controller.ts
spec/swagger-decorator/swagger-decorator.spec.ts
spec/swagger-decorator/update-request.dto.ts
src/lib/crud.route.factory.ts
src/lib/interface/decorator-option.interface.ts

-   [ ] Bugfix
My plan was that the `@ApiBody decorator` would be used to override the Swagger body.
```
@Crud({
entity: ReferenceCodeEntity,
routes: {
[Method.UPDATE]: {
decorators: [
ApiBody({
type: UpdateReferenceCodeRequestDto,
}),
],
},
},
})
```
I found that the other …

feat: override swagger body

---

src/lib/crud.policy.ts
src/lib/crud.route.factory.spec.ts
src/lib/crud.route.factory.ts

-   [ ] Bugfix
In auto-generated swagger docs, paginationType is not reflected for the search route. 
In the case of readMany, the type of the query parameter and the response body varies depending on the paginationType.
Now paginationType is also reflected in the document …

feat: updated to swagger docs reflect the paginationType for search

---

README.ko.md
README.md
spec/logging/logging.spec.ts
spec/pagination/pagination.spec.ts
spec/pagination/view-entity-pagination.module.ts
spec/pagination/with-pagination-keys.spec.ts
spec/test.helper.ts
src/lib/crud.route.factory.spec.ts
src/lib/crud.route.factory.ts
src/lib/interceptor/create-request.interceptor.spec.ts
src/lib/interceptor/delete-request.interceptor.spec.ts
src/lib/interceptor/read-many-request.interceptor.spec.ts
src/lib/interceptor/read-many-request.interceptor.ts
src/lib/interceptor/read-one-request.interceptor.spec.ts
src/lib/interceptor/recover-request.interceptor.spec.ts
src/lib/interceptor/search-request.interceptor.spec.ts
src/lib/interceptor/search-request.interceptor.ts
src/lib/interface/decorator-option.interface.ts
src/lib/interface/factory-option.interface.ts
src/lib/request/read-many.request.ts

-   [ ] Bugfix
Issue Number: #456
- provide paginationKeys as options for readMany and search route.
- if paginationKeys are not explicitly set, primary keys are set as default.
- cursor for pagination operates based on the pagination keys.
- returned items are sorted by pagination keys.
-   [ …

feat: added paginationKeys as @Crud options in search and readMany

---

spec/base/base.controller.spec.ts
spec/exclude-swagger/exclude-swagger.spec.ts
src/lib/crud.decorator.spec.ts
src/lib/crud.decorator.ts

-   [ ] Bugfix
It does not validate whether CrudService has been properly inserted as a member in the controller. 
This leads to undefined reference errors when the API is called later.
It validates at the time of the instantiation of controller to check if CrudService is …

feat: add validation to check if CrudService is included as member of controller

---

spec/exclude-swagger/exclude-swagger.spec.ts
src/lib/crud.route.factory.spec.ts
src/lib/crud.route.factory.ts
src/lib/request/read-many.request.ts

-   [ ] Bugfix
When using OmitType or PickType in the swagger.body configuration, the schema name become PickTypeClass or OmitTypeClass.
It uses schema name which reflect crud method, table name, and source.
ex) 'create' route, 'base' table, request body -> CreateBaseBodyDto …

feat: changed request body schema name when using omitted/picked type

---

src/lib/crud.service.ts
src/lib/interceptor/search-request.interceptor.spec.ts
src/lib/interceptor/search-request.interceptor.ts
src/lib/provider/typeorm-query-builder.helper.ts

-   [ ] Bugfix
When invalid request body is sent to the search route, the error message returned is ambiguous. 
It makes it difficult to determine from the message which part of the request is invalid.
Test cases for validation are not grouped in detail, making them difficult to understand. …

refactor: improve validation for search route and refactor test code

---

spec/pagination/pagination.spec.ts
src/lib/abstract/abstract.pagination.spec.ts
src/lib/abstract/abstract.pagination.ts
src/lib/abstract/abstract.request.interceptor.ts
src/lib/dto/request-search.dto.ts
src/lib/interceptor/read-many-request.interceptor.ts
src/lib/interceptor/search-request.interceptor.ts

-   [ ] Bugfix
When invalid value is passed to nextCursor in a search or readMany request, any specified where condition in the request is ignored, and no filtering is applied.
When nextCursor is invalid, items are filtered based on specified where condition (search - …

feat: modified to filter items based on options in request when nextCursor is invalid

---

spec/exclude-swagger/exclude-swagger-resonse-name.spec.ts
spec/exclude-swagger/exclude-swagger.spec.ts
src/lib/crud.decorator.ts

-   [x] Bugfix
Issue Number: #558
operationId in swagger docs does not reflect controller name.
It occurs because decorator returns an anonymous class that extends target controller.
'name' of the returned class is specified as the original controller name.
operationId in swagger docs is like …

fix: fixed so that name of extended controller follow original name

---

spec/pagination/pagination.spec.ts
src/lib/interceptor/read-many-request.interceptor.ts
src/lib/interceptor/search-request.interceptor.spec.ts
src/lib/interceptor/search-request.interceptor.ts
src/lib/request/read-many.request.ts

-   [ ] Bugfix
In cursor pagination, both ‘limit’ and ‘offset’ can be used.
Issue Number: #571 
In cursor pagination, only ‘offset’ can be used.
In offset pagination, only ‘limit’ can be used.
-   [ ] Yes
-   [x] No
separated PR from #579

feat: only take can be used in cursor pagination, not limit

---

spec/search/search-cursor-pagination.spec.ts
src/lib/interceptor/read-many-request.interceptor.ts
src/lib/interceptor/search-request.interceptor.spec.ts
src/lib/interceptor/search-request.interceptor.ts
src/lib/request/read-many.request.ts

-   [ ] Bugfix
During the validation stage, `withDeleted` was assigned redundantly with default values, and this was being serialized in the query(nextCursor).
`setSort` and `setOrder` both set the sort and order, making their roles unclear.
Default value for `withDeleted` is …

refactor:  improve the logic for setting options in readMany and search
