woowabros/nestjs-library-crud

README.md
-   [ ] Bugfix
- Fix link in the readme
-   [ ] Yes
-   [x] No
=> Fix link in the readme

.github/workflows/codeql-analysis.yml
-   [ ] Bugfix
Enable CodeQL analysis to provide analysis report to maintainers and contributors.
-   [ ] Yes
-   [x] No
=> feat: enable codeql-analysis

README.md
-   [ ] Bugfix
- Fix wrong contributors url
-   [ ] Yes
-   [x] No
=> docs: fix wrong contributors url

package.json
-   [ ] Bugfix
- I modified it `directly in the main branch` when deploying.
- I no longer modify directly in the main branch.
- We need to discuss `how to manage` package json, release notes, tags, etc. when deploying.
- Changes to package.json due to this 0.4.2 release
- …
=> build: release 0.4.2

README.ko.md
-   [ ] Bugfix
Improve `readme` of Korean version
-   [ ] Yes
-   [x] No
=> docs: readme kor version

package.json
-   [ ] Bugfix
-   [x] Other... Please describe:
release v0.4.3
-   [ ] Yes
-   [x] No
I'm hoping that the `changes to the README` will be reflected in npm.
=> chore: release v0.4.3

.github/workflows/ci.yml, jest.config.ts, package.json
-   [ ] Bugfix
Even though we are collecting test coverage, it's not accessible easily. When we want to check test coverage, we need to check log of Github CI action. 
Maintainer/Contributor can check test coverage of current codebase or pull request.
-   [ ] Yes
-   [x] No
- …
=> feat: integrate coveralls

.github/dependabot.yml
-   [ ] Bugfix
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates
-   [ ] Yes
-   [x] No
=> feat: dependabot.yml

package.json, yarn.lock
Reverts woowabros/nestjs-library-crud#111
=> Revert "build(deps-dev): bump eslint from 8.39.0 to 8.40.0"

src/lib/interface/decorator-option.interface.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: add interface comment

src/lib/abstract/abstract.request.interceptor.spec.ts, src/lib/abstract/abstract.request.interceptor.ts, src/lib/interface/author.interface.ts
-   [ ] Bugfix
- `getAuthor` method takes author information from the request object.
-   [ ] Yes
-   [x] No
Test code might be excessive but I tried to cover all possible methods. Please tell me idea to reduce them, then I will update them.
=> feat: simplify expression

package.json
-   [ ] Bugfix
-   [x] Build related changes
release v0.4.5
-   [ ] Yes
-   [x] No
=> chore: release v0.4.5

package.json
-   [X] Bugfix
Issue Number: #189 
-   [ ] Yes
-   [X] No
=> fix: remove module type in package.json

package.json
-   [ ] Bugfix
-   [x] Build related changes
release v0.4.6
-   [ ] Yes
-   [x] No
=> chore: release v0.4.6

package.json
-   [ ] Bugfix
-   [x] Build related changes
-   [ ] Yes
-   [x] No
=> chore: release v0.4.7

package.json, src/lib/override.decorator.ts
-   [ ] Bugfix
-   [ ] Other...Please describe:
An `experimental feature`, the Override decorator was an `early specification` for the library.
The library thought it could `replace complex requirements` through override.
I think the Nestjs Cycle(interceptor, guard, filter...) allows for `customization …
=> deprecated Override decorator

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.5.0
-   [ ] Yes
-   [ ] No
=> chore: release v0.5.0

spec/pgsql/pgsql.spec.ts
-   [ ] Bugfix
-   [x] Other... Please describe:
pgsql unit-test
-   [ ] Yes
-   [x] No
=> feat: pgsql unit-test

src/lib/provider/index.ts
-   [ ] Bugfix
- Expose `crud-logger` class to reuse with standard interceptors
-   [ ] Yes
-   [x] No
=> feat: expose crud logger

.eslintrc.cjs, lint-staged.config.cjs, spec/pgsql/pgsql.spec.ts, spec/relation-entities/comment-relation.interceptor.ts, spec/request-interceptor/delete.request.interceptor.ts, spec/request-interceptor/read-one.request.interceptor.ts, spec/response-interceptor/response-custom.interceptor.ts, src/lib/crud.route.factory.ts, src/lib/interceptor/search-request.interceptor.ts
-   [ ] Bugfix
-   [x] Code style update (formatting, local variables)
There are unclear type conversions in codebase as following code snippet.
```ts
const b = !!foo;
const n = +foo;
```
Using more explanatory notation could increase readability of codebase compared to using short notation.
Apply `no-implicit-coercion` eslint …
=> feat: apply no-implicit-coercion eslint rule

spec/changed-error-message/duplicated.spec.ts, spec/changed-error-message/test.module.ts
-   [ ] Bugfix
Test case: How to changed the error message.
Guides how to change the error message.
-   [ ] Yes
-   [x] No
=> Test case: How to changed the error message 

spec/exclude-swagger/exclude-swagger.spec.ts, src/lib/crud.route.factory.ts
-   [ ] Bugfix
-   [x] Code style update (formatting, local variables)
swagger definition for createMany.
- Defines that the body can act as an Array in Swagger.
-   [ ] Yes
-   [x] No
=> swagger definition for createMany.

package.json
-   [ ] Bugfix
-   [v] Build related changes
release v0.7.0 (https://github.com/woowabros/nestjs-library-crud/releases/tag/0.7.0) 
-   [ ] Yes
-   [ ] No
=> chore: release v0.7.0

package.json, spec/custom-entity/custom-entity.controller.search.spec.ts, spec/search/search-cursor-pagination.spec.ts, src/lib/interceptor/search-request.interceptor.ts
-   [x] Bugfix
If `order` is not defined in 'Search', nextPage may be incorrect.
If `order`  is not defined in 'Search',  define the default order.
-   [ ] Yes
-   [x] No
=> should be defined `default order` in 'Search'

package.json
-   [ ] Bugfix
-   [x] Build related changes
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.7.1
-   [ ] Yes
-   [ ] No
=> chore: release v0.7.1

package.json, yarn.lock
-   [ ] Bugfix
chore: bump up libraries
-   [ ] Yes
-   [x] No
=> chore: bump up libraries

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.8.1
-   [ ] Yes
-   [ ] No
=> chore: release v0.8.1

package.json
-   [ ] Bugfix
release v0.8.2
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.8.2
-   [ ] Yes
-   [x] No
=> chore: release v0.8.2

package.json
-   [ ] Bugfix
Release 0.8.3
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.8.3
-   [ ] Yes
-   [ ] No
=> chore: release v0.8.3

package.json
-   [ ] Bugfix
release v0.8.4 (https://github.com/woowabros/nestjs-library-crud/releases/tag/0.8.4)
-   [ ] Yes
-   [ ] No
=> chore: release v0.8.4

package.json, src/lib/interceptor/search-request.interceptor.ts
-   [x] Bugfix
When next page request, entities that do not matched conditions are searched.
The next page of the search contains unnecessary conditions.
-   [ ] Yes
-   [x] No
=> fix: next page bug on search

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.8.5
-   [ ] Yes
-   [ ] No
=> chore: release v0.8.6

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.8.7
-   [ ] Yes
-   [ ] No
=> chore: release v0.8.7

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.8.8
-   [ ] Yes
-   [ ] No
=> chore: release v0.8.8

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.9.0
-   [ ] Yes
-   [ ] No
=> chore: v0.9.0

.github/workflows/ci.yml
-   [ ] Bugfix
exclude node 16.x
-   [ ] Yes
-   [ ] No
=> exclude node 16.x

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.10.0
-   [ ] Yes
-   [ ] No
=> chore: release v0.10.0

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.10.1
-   [ ] Yes
-   [ ] No
=> chore: release v0.10.1

spec/pagination/pagination.spec.ts
-   [ ] Bugfix
-   [x] Other... Please describe: unit-test
Issue Number: #432
unit-test to fetch data with offset pagination
-   [ ] Yes
-   [x] No
=> feat: unit-test to fetch data with offset pagination

spec/pagination/pagination.interceptor.spec.ts, spec/pagination/pagination.spec.ts, spec/pgsql/pgsql.spec.ts, spec/search/search-complex-condition.spec.ts, spec/sub-path/sub-path-more-than-one-parent.spec.ts, spec/sub-path/sub-path-one-parent.spec.ts, src/lib/dto/pagination-offset.dto.spec.ts, src/lib/dto/pagination-offset.dto.ts, src/lib/provider/pagination.helper.spec.ts
-   [ ] Bugfix
Issue Number: #432 
allowed zero on 'offset', and remove maximum value on 'limit'
fixed broken unit-test on node v20.
-   [ ] Yes
-   [x] No
=> feat: allowed offset zero, and remove limit`s maximum value

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.10.2
-   [ ] Yes
-   [x] No
=> chore: release v0.10.2

src/lib/interceptor/search-request.interceptor.spec.ts, src/lib/interceptor/search-request.interceptor.ts
-   [ ] Bugfix
-   [x] Other... Please describe: unit test
Added test case for SearchRequestInterceptor.
Fixed typo in test name.
Test coverage was improved
-   [ ] Yes
-   [x] No
Hi there!
I was interested in your amazing work. 
I added some test cases that appear to be missing.
=> feat: added test case, remove unnecessary optional chaining

spec/embedded-entities/embedded-entites.spec.ts, spec/naming-strategy/embedded-entites.spec.ts, spec/naming-strategy/naming-stategy.spec.ts, spec/naming-strategy/snake-naming.strategy.ts, spec/test.helper.ts, src/lib/crud.service.ts
-   [x] Bugfix
Issue Number: #463 
There is an issue where 'column' is not defined correctly when using `namingStrategy`.
This is a `side effect` of `supporting embedded entities`.
fix column wrong defined when use  namingStrategy.
-   [ ] Yes
-   [x] No
=> fix: column wrong defined when use  namingStrategy

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.11.1
-   [ ] Yes
-   [x] No
=> chore: release v0.11.1

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.12.0
-   [ ] Yes
-   [ ] No
=> chore: release v0.12.0)

README.md
star history
-   [ ] Bugfix
https://star-history.com/
-   [ ] Yes
-   [x] No
=> docs: star history

package.json
-   [ ] Bugfix
https://github.com/woowabros/nestjs-library-crud/releases/tag/0.12.1
-   [ ] Yes
-   [ ] No
=> release v0.12.1

spec/search/module.ts, spec/search/search-cursor-pagination.spec.ts, spec/search/search-query-operator.spec.ts, src/lib/interceptor/search-request.interceptor.spec.ts
-   [ ] Bugfix
-   [x] Other... Please describe: add test case
There was no existing test case for 'where' filter on date column
Issue Number: #553 
added test case for 'where' filter on a date value in the search request.
-   [ ] Yes
-   [x] No
=> test: add test case for date comparison in search route

.github/workflows/ci.yml
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> chore: bump up github actions/cache version
